import { Cabin } from 'next/font/google';
import './globals.css';

const cabin = Cabin({
  subsets: ['latin'],  // You can specify subsets here
  weight: ['400', '700'],  // Specify font weights you want to use
  variable: '--font-cabin',  // Custom CSS variable for the font
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cabin.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
